#!/bin/bash

#################################
## This scripts startss cm/web services
##
## Suneel Tirunamala  05/10/2012 Initial Script Template
##
##
## Argument 1: <lower instancename > {MANDATORY}
## Argument 2: This should not be used at all. This argument is 
## required for script execution.
##
################################

. /shared/scripts/clone/conf/${1}_refresh.env

f_start_app()
{

f_echo "*****************************"
f_echo "In function f_start_app"

f_echo "Starting the Processes using adstrtal.sh"

  f_echo "Preparing temporary script to start services"
  PERL_SCRIPT=${TEMP_LOG_LOC}/perl_temp.pl
  rm -f $PERL_SCRIPT $TEMP_FILE
  if [ "$?" != "0" ]
  then
    f_echo "ERROR: Not able to delete temporary perl script $PERL_SCRIPT or $TEMP_FILE"
    exit;
  fi

  cat ${COMMONFILES}/perl_sub.pl  >> $PERL_SCRIPT
  echo "runPipedCmd(\"${1} \", \"APPS\",\"$APPS_PSWD\", \"$WL_PASSWD\"  );" >> $PERL_SCRIPT

  chmod 755 $PERL_SCRIPT
  cat $PERL_SCRIPT >> $LOG_FILE 2>>$LOG_FILE

  f_echo "Starting services    "
  f_echo "You may monitor the progress in $TEMP_FILE"

  /usr/bin/perl $PERL_SCRIPT  >>$TEMP_FILE 2>>$TEMP_FILE

  cat ${TEMP_FILE} >> ${LOG_FILE}

f_echo "grep Exiting with status 0 ${TEMP_FILE}" >> ${LOG_FILE}
grep "Exiting with status 0" ${TEMP_FILE} >> ${LOG_FILE} 2>> ${LOG_FILE}
if [ "$?" = "0" ]
then
   f_echo "SUCCESS:adstrtal.sh completed successfully."
else
   f_echo "ERROR: adstrtal.sh is not successful."
   ERROR="Y"
fi

f_echo "Exiting from function f_start_app"
f_echo "*********************************" 
  
}

#Main 

ERROR="N"
APPS_PSWD=`GetPassword APPS`
WL_PASSWD=`GetPassword WEBLOGIC`
TEMP_LOG_FILE=${TEMP_LOG_LOC}/start_services

f_echo "Started $0 (Arguments: $@)"
f_check_run_fs

if [ "$#" = "1" ]
then

 for i in $NODE_START_DIR
 do
  NODE=`echo $i | awk -F: '{print $1}'`
  START_SCR=`echo $i | awk -F: '{print $2}'`
  ENV_FILE=`echo $i | awk -F: '{print $3}'`
  f_echo "Trying to start proccess on $NODE "
  f_echo "$SSH ${APUSER}@${NODE} $START_SERVICES_SCRIPT ${LINSTANCE} $START_SCR $NODE $ENV_FILE" 
  $SSH ${APUSER}@${NODE} $START_SERVICES_SCRIPT ${LINSTANCE} $START_SCR $NODE $ENV_FILE
  if [ -f ${TEMP_LOG_LOC}/${NODE}_START_SERVICES_SUCCESS ]
  then
     f_echo "SUCCESS: Services on $NODE are started successfully."
  else
     f_echo "ERROR: Services on $NODE are not started."
     f_echo "ERROR: Please review the log and process and rerun the script."
     exit
   fi
 done

touch ${START_SERVICES_SUCCESS}

elif [ "$#" = "4" ]
then
  f_echo "Sourcing the environment file:$4"
  . $4
  ERROR="N"
  rm -f  ${TEMP_LOG_LOC}/${3}_START_SERVICES_SUCCESS
  if [ "$?" != "0" ]
  then
      f_echo "ERROR: Not able to delete previous success file ${TEMP_LOG_LOC}/${3}_START_SERVICES_SUCCESS on $DB_NODE"
      exit;
  fi
  f_start_app $2
  if [ "$ERROR" = "N" ]
  then
    f_echo "SUCCESS: Services on `hostname` started successfully."
    f_echo "creating the success flag file ${TEMP_LOG_LOC}/${3}_START_SERVICES_SUCCESS"
    touch ${TEMP_LOG_LOC}/${3}_START_SERVICES_SUCCESS >>$LOG_FILE 2>>$LOG_FILE
  else
    f_echo "ERROR: Services on `hostname` are not started successfully."
  fi
fi

f_echo "Completed $0"
exit
